# databases:
#   - name: postgres
#     ipAllowList: []

# services:
#   - type: web
#     name: movie-list
#     env: ruby
#     buildCommand: "./bin/render-build.sh"
#     startCommand: bundle exec rails s
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: postgres
#           property: connectionString
#       - key: RAILS_MASTER_KEY
#         sync: false

#       - type: redis
#         name: redis
#         ipAllowList: []
#         plan: free
#         maxmemoryPolicy: noeviction



databases:
  - name: postgres
    databaseName: movie_list
    user: nanmartins

services:
  - type: web
    name: postgres
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

      - type: redis
        name: redis
        ipAllowList: []
        plan: free
        maxmemoryPolicy: noeviction
