databases:
  - name: postgres
    ipAllowList: []

services:
  - type: web
    name: movie-list
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: aa9ec8c6a0aff28b5358dbb94601b61e
        sync: false

      - type: redis
        name: redis
        ipAllowList: []
        plan: free
        maxmemoryPolicy: noeviction
