SCALINGO_POSTGRESQL_URL=postgres://movie_list_2331:Rt70FQTNSeOSU44Ql7-3@movie-list-2331.postgresql.a.osc-fr1.scalingo-dbs.com:30265/movie_list_2331?sslmode=prefer

DATABASE_MOVIE_USERNAME=nanmartins

DATABASE_MOVIE_PASSWORD=Nan13121989!
